### ISSUE TITLE
IndexError: list index out of range while training

### ISSUE THREAD

**Issue by newdev7** [golastmile/rasa_nlu#111]
Hi,

I tried to migrate a wit.ai app to rasa.ai. I exported the wit.ai data. In the config.json file, I added the expressions.json file for data. When I tried to train the rasa.ai with the expressions.json file, it shows num train for 525 samples and it almost took 8 hours and returns in an error.

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.macosx-10.11-intel/egg/rasa_nlu/train.py", line 65, in <module>
  File "build/bdist.macosx-10.11-intel/egg/rasa_nlu/train.py", line 59, in do_train
  File "build/bdist.macosx-10.11-intel/egg/rasa_nlu/trainers/mitie_trainer.py", line 25, in train
  File "build/bdist.macosx-10.11-intel/egg/rasa_nlu/trainers/mitie_trainer.py", line 42, in train_entity_extractor
  File "build/bdist.macosx-10.11-intel/egg/rasa_nlu/trainers/mitie_trainer.py", line 31, in start_and_end
IndexError: list index out of range
```

How to resolve this error. Thanks.

**Comment by amn41** [comment]
thanks for reporting this. It looks like an issue trying to match an entity to a value in a sentence. Could you please share your training data? You can also just email it to me (email on my profile). 
Also, if training is taking a long time consider using [my MITIE fork](https://github.com/amn41/MITIE).

**Comment by nmstoker** [comment]
Thank you for this!

Updating to the latest version (ie including e596169) helped me with what would've been a very hard to catch problem in my training data (the problem was an entity that occurred at an earlier point in the sentence too, within another word!)

BTW have you done something to speed things up? It seems faster (I was on 0.4.2.1 before moving to 0.5.0.0) I hadn't got round to using your MITIE fork yet but this already appears improved (although not quite finished training, it got further in a shorter time)
