### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by guillegette** [golastmile/rasa_nlu#145]
Hi guys,

I am new to Python, sorry if this is a trivial question. I was able to get the server up and running with spaCy + scikit-learn. I was able to create a training model but when I start the server and run a query I get this error:

```
Exception happened during processing of request from ('127.0.0.1', 56865)
Traceback (most recent call last):
  File "/Users/gette/anaconda2/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Users/gette/anaconda2/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/Users/gette/anaconda2/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/server.py", line 81, in <lambda>
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/server.py", line 165, in __init__
  File "/Users/gette/anaconda2/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/Users/gette/anaconda2/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/Users/gette/anaconda2/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/server.py", line 191, in do_GET
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/server.py", line 181, in get_response
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/server.py", line 110, in parse
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/interpreters/spacy_sklearn_interpreter.py", line 48, in parse
    entities = self.get_entities(text)
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/interpreters/spacy_sklearn_interpreter.py", line 38, in get_entities
    return self.extractor.extract_entities(self.nlp, text)
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/extractors/spacy_entity_extractor.py", line 46, in extract_entities
    print(nlp.tagger(doc))
TypeError: 'NoneType' object is not callable
```

Command to start the server:
`$ python -m rasa_nlu.server -c config_example.json --server_model_dir=./model_20170207-215249/`

My model folder:
```
-rw-r--r--  1 gette  staff  55519  7 Feb 21:52 intent_classifier.pkl
-rw-r--r--  1 gette  staff    365  7 Feb 21:52 metadata.json
drwxr-xr-x  4 gette  staff    136  7 Feb 21:52 ner
-rw-r--r--  1 gette  staff   5991  7 Feb 21:52 training_data.json
```

I start adding some `print` around the code to know where was failing and looks to be [here](https://github.com/golastmile/rasa_nlu/blob/master/src/extractors/spacy_entity_extractor.py#L42)

Last but not least, I am running the latest version of rasa_nlu, Python 2.7.13 on Mac OSX 10.11.5

Let me know if you need any more info. Thanks!

**Comment by amn41** [comment]
Have you downloaded the spacy data for your language? try e.g. `python -m space.en.download all` https://spacy.io/docs/usage/

**Comment by guillegette** [comment]
Hi @amn41 I thought that I updated the issue, sorry for that! Yes, that was the problem, I forgot to install the spacy data :( Literally as soon as I finished posting this I thought about checking that. Keep up the awesome work!

**Comment by tmbo** [comment]
@guillegette No worries, the issue was helpfull anyway. I added an exception that catches this error in a meaningful way. So future users shouldn't run into the `TypeError: 'NoneType' object is not callable` issue.
