### ISSUE TITLE
ImportError: No module named sklearn.model_selection

### ISSUE THREAD

**Issue by atiquenazar** [golastmile/rasa_nlu#162]
unable to setup spacy backend
python -m rasa_nlu.train -c config_spacy.json
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build\bdist.win32\egg\rasa_nlu\train.py", line 67, in <module>
  File "build\bdist.win32\egg\rasa_nlu\train.py", line 56, in do_train
  File "build\bdist.win32\egg\rasa_nlu\train.py", line 33, in create_trainer
  File "build\bdist.win32\egg\rasa_nlu\trainers\spacy_sklearn_trainer.py", line 8, in <module>
  File "build\bdist.win32\egg\rasa_nlu\classifiers\sklearn_intent_classifier.py", line 4, in <module>
ImportError: No module named sklearn.model_selection

**Comment by amn41** [comment]
see #157

**Comment by abubakarsohail** [comment]
Hey @amn41 , since someone else is having the same issue as mine. Can you please help me resolve the issue?
