### ISSUE TITLE
ImportError: No module named model_selection

### ISSUE THREAD

**Issue by vinnitu** [golastmile/rasa_nlu#177]
get after fresh install

```
$ python -m rasa_nlu.train -c config_spacy.json
/usr/local/lib/python2.7/dist-packages/rasa_nlu-0.6b0-py2.7.egg/rasa_nlu/__init__.py:1: UserWarning: Module rasa_nlu was already imported from /usr/local/lib/python2.7/dist-packages/rasa_nlu-0.6b0-py2.7.egg/rasa_nlu/__init__.pyc, but /tmp/rasa_nlu is being added to sys.path
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/rasa_nlu/train.py", line 73, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_nlu/train.py", line 61, in do_train
  File "build/bdist.linux-x86_64/egg/rasa_nlu/train.py", line 36, in create_trainer
  File "build/bdist.linux-x86_64/egg/rasa_nlu/trainers/spacy_sklearn_trainer.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_nlu/trainers/sklearn_trainer_utils.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_nlu/classifiers/sklearn_intent_classifier.py", line 4, in <module>
ImportError: No module named model_selection
```

**Comment by amn41** [comment]
this is probably a version issue with scikit-learn. Which version do you have installed?

**Comment by vinnitu** [comment]
yea... it was... You are right

after 
```
$ sudo -H pip2 install -U scikit-learn
Collecting scikit-learn
  Downloading scikit_learn-0.18.1-cp27-cp27mu-manylinux1_x86_64.whl (11.6MB)
...
```
it works
