### ISSUE TITLE
Issue when running trainer- Question

### ISSUE THREAD

**Issue by kumar-b5** [golastmile/rasa_nlu#179]
Hi,

I am trying to learn NLU and ML. this is the first tool I have tried. I have build mitie as shared library and trying to run rasa, however , I am getting the following error when running . I am running this from centos7 docker container.

python -m rasa_nlu.train -c config.json
/usr/lib/python2.7/site-packages/rasa_nlu-0.6_beta-py2.7.egg/rasa_nlu/__init__.py:1: UserWarning: Module rasa_nlu was already imported from /usr/lib/python2.7/site-packages/rasa_nlu-0.6_beta-py2.7.egg/rasa_nlu/__init__.pyc, but /home/rasa is being added to sys.path
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/rasa_nlu/train.py", line 67, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_nlu/train.py", line 56, in do_train
  File "build/bdist.linux-x86_64/egg/rasa_nlu/train.py", line 30, in create_trainer
  File "build/bdist.linux-x86_64/egg/rasa_nlu/trainers/mitie_trainer.py", line 2, in <module>
ImportError: No module named mitie

**Comment by kumar-b5** [comment]
No longer an issue

**Comment by Tr-off** [comment]
Could you please advise how this was resolved? In general, how to setup mitie on Windows (for example, using pre-build windows package)?

**Comment by kumar-b5** [comment]
I was using this in linux environment, I had issue due to mitie path not available in python import. , I ran the training from mitlilab folder, it worked.  Not sure how it would run from windows, if you experience the same issue, running code from mitielab folder would work.

**Comment by ankitarath2011** [comment]
You can append mitielib path to sys.path
