### ISSUE TITLE
MemoryError when spacy_sklearn with fine_tune_spacy_ner : true

### ISSUE THREAD

**Issue by steookk** [golastmile/rasa_nlu#184]
Hi, today I wanted to give a try to this new option but I immediately get a memory error.
The error happens each single time.
Maybe have you already experienced this?
I have 16GB of RAM, the error happened when about 11GB were used, of which around 2GB used by rasa.
Thanks for your help!

python -m rasa_nlu.train -c config_en.json
Traceback (most recent call last):
  File "/usr/local/miniconda2/installation/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/miniconda2/installation/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/train.py", line 73, in <module>
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/train.py", line 66, in do_train
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/trainers/trainer.py", line 28, in train
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/trainers/spacy_sklearn_trainer.py", line 26, in train_entity_extractor
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/extractors/spacy_entity_extractor.py", line 33, in train
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/extractors/spacy_entity_extractor.py", line 48, in _fine_tune
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/extractors/spacy_entity_extractor.py", line 60, in _update_ner_model
  File "spacy/syntax/parser.pyx", line 261, in spacy.syntax.parser.Parser.update (spacy/syntax/parser.cpp:8032)
  File "thinc/linear/avgtron.pyx", line 220, in thinc.linear.avgtron.AveragedPerceptron.updateC (thinc/linear/avgtron.cpp:5314)
  File "thinc/linear/avgtron.pyx", line 228, in thinc.linear.avgtron.AveragedPerceptron.update_weight (thinc/linear/avgtron.cpp:5510)
  File "thinc/linear/avgtron.pyx", line 138, in thinc.linear.avgtron.AveragedPerceptron.resume_training (thinc/linear/avgtron.cpp:4177)
MemoryError: Error allocating memory for feature: 331945041020846080

**Comment by tmbo** [comment]
@steookk do you mind sending me your configuration? tom@golastmile.com

**Comment by tmbo** [comment]
@steookk I just tried it locally using the following configuration:
```

**Comment by steookk** [comment]
It still happens. I'm going to try on a different mac tomorrow and let you know.

**Comment by steookk** [comment]
hey, I tried on a different mac with a fresh python installation done via miniconda and the same problem happened. It happens in both english and german, so language does not matter.

Maybe we should exclude that it is not due to miniconda or some packages that it provides: could you try with a fresh installation of miniconda or could you explain me how to setup spacy + scikit_learn via pip (I tried installing the single packages via pip but the model train terminates with no results) ?

**Comment by tmbo** [comment]
@steookk Yes I think there is not much output the sklearn trainer generates, did it create a new model directory with a spacy_sklearn model?

**Comment by steookk** [comment]
@tmbo I am pretty sure it wasn't creating anything at all but I can check again

**Comment by steookk** [comment]
@tmbo I was remembering wrongly, it generates a model with fine_tune_spacy_ner : false  (useless one because it doesn't get anything right, if I'm not wrong we need 5000+ examples to make it of a good level, right?) 
But with fine_tune_spacy_ner : true the same memory problem appears, so it's not caused by miniconda..

**Comment by tmbo** [comment]
@steookk I am unable to reproduce this error, it does work fine for me. Anyway, this does not seem to be a rasa NLU issue, but rather a spacy one. Which version of spacy are you using?

**Comment by tmbo** [comment]
Happens with the latest spacy version (1.6.0)...

**Comment by tmbo** [comment]
This is resolved, though fine tuning works different now. Waiting on spacy 2.0 to be released to revisit the finetuning. Fine tuning is still present, but its a stacked entity recognition, e.g. first the user trained model will be applied and found entities will be added, afterwards the spacy internal model will be run and any no yet found entities will be added to the result.
