### ISSUE TITLE
Rasa won't load the model

### ISSUE THREAD

**Issue by jplorandi** [golastmile/rasa_nlu#185]
I'm getting a stacktrace:

```
Error loading MITIE model file: ./models/model_20170216-085530/entity_extractor.dat
std::bad_alloc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/rasa_nlu/server.py", line 255, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_nlu/server.py", line 21, in __init__
  File "build/bdist.linux-x86_64/egg/rasa_nlu/server.py", line 55, in __create_interpreter
  File "build/bdist.linux-x86_64/egg/rasa_nlu/interpreters/mitie_interpreter.py", line 12, in __init__
  File "/usr/local/lib/python2.7/site-packages/mitie/mitie.py", line 247, in __init__
    raise Exception("Unable to load named entity extractor from " + filename)
Exception: Unable to load named entity extractor from ./models/model_20170216-085530/entity_extractor.dat
```

I'm trying to confirm whether this is a RAM issue -- it happens in Docker but some of the other lads at the office are experiencing the same, across platforms.

**Comment by jplorandi** [comment]
This also happens when using as a library, from python.

**Comment by tmbo** [comment]
Which versions of mitie & rasa NLU are you using?

**Comment by jplorandi** [comment]
I'm installing in a docker instance via:
```
RUN apt-get update -qq && apt-get install -y --no-install-recommends \
  build-essential \
  git-core && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
  pip install -r "${RASA_NLU_HOME}/requirements.txt"
```

Also, another dockerfile has:
```
RUN pip install git+https://github.com/mit-nlp/MITIE.git \
    && pip install -U scikit-learn

RUN git clone https://github.com/golastmile/rasa_nlu.git \
    && mv rasa_nlu /usr/src \
    && cd /usr/src/rasa_nlu \
    && python setup.py install \
    && mkdir models

```

So basically, HEAD for both MITIE and rasa_nlu.

**Comment by tmbo** [comment]
@jplorandi are you using the `mitie_sklearn` backend?

**Comment by jplorandi** [comment]
Both `mitie` and `mitie_sklearn` -- I have trained using only mitie, offline, so I don't think this is specific to the new sklearn support.

**Comment by steookk** [comment]
I get the same error (only with mitie_sklearn)..

**Comment by jplorandi** [comment]
ok, so I’m trying to create a Dockerfile. I have a Dockerfile and two folders `data` with MITIE’s `total_word_feature_extractor` in it and `files` is the other folder, with a config.json like so:
```
{
  "backend": "mitie",
  "mitie_file": "./data/total_word_feature_extractor.dat",
  "path" : "./",
  "data" : "./data/examples/rasa/demo-rasa.json",
  "server_model_dir": "./models/model_20170228-135450"
}
```

And the Dockerfile itself:
```
#Azumo Rasa Dockerfile
FROM python:2.7.13

RUN pip install git+https://github.com/mit-nlp/MITIE.git \
    && pip install -U scikit-learn

RUN git clone https://github.com/golastmile/rasa_nlu.git \
    && mv rasa_nlu /usr/src \
    && cd /usr/src/rasa_nlu \
    && pip install -r requirements.txt \
    && python setup.py install \
    && mkdir models


WORKDIR /usr/src/rasa_nlu

COPY ./data/ ./data/

#RUN pip install -U spacy
#RUN python -m spacy.en.download all

COPY ./files/ .

RUN chmod +x ./start.sh

EXPOSE 5000
VOLUME [ "/usr/src/rasa_nlu/models" ]

#ENTRYPOINT [ "./start.sh" ]
CMD [ "/bin/bash" ]
```

You build this normally, i.e.:
`docker build -t rasa_nlu .`

You then can start it in bash mode like this:
`docker run -i -P -v /path/to/folder/containing/models:/usr/src/rasa_nlu/models rasa_nlu`

I then manually run to start the server:
`python -m rasa_nlu.server -c config.json`

**Comment by jplorandi** [comment]
`start.sh` has:
```
#!/usr/bin/env bash

set -e

case ${1} in
    start)
        exec python -m rasa_nlu.server -c ./config.json
        ;;
esac
```

**Comment by jplorandi** [comment]
I'm attaching my model files here...
[Archive.zip](https://github.com/golastmile/rasa_nlu/files/809299/Archive.zip)

**Comment by tmbo** [comment]
The bad alloc is most likely due to the mitie file not beeing found. Make sure you've set `mitie_file` correctly.

I've improved the error message on the soon-to-be-merged multitenancy branch.
