### ISSUE TITLE
Question regarding Mitie backend with 'de'

### ISSUE THREAD

**Issue by steookk** [golastmile/rasa_nlu#187]
I experimented the use of Mitie backend with 'de' language (with de feature extractor, while I just hoped the tokenizer would work). It seemed to work till I got the error below.
Is this the reason (or are there other reasons) why 'de' is not 'allowed' to be used with Mitie? 

now do training
num training samples: 164
C: 200   f-score: 0.71875
C: 400   f-score: 0.71875
C: 300   f-score: 0.725
C: 310   f-score: 0.725
C: 250   f-score: 0.71875
C: 305   f-score: 0.71875
C: 302.5   f-score: 0.73125
C: 302.083   f-score: 0.725
C: 303.385   f-score: 0.725
C: 302.734   f-score: 0.725
best C: 302.5
test on train:
65  0  0  1  0  0  0
 0 11  0  0  0  0  0
 0  0 21  1  0  0  0
 0  0  0 39  0  0  0
 0  0  0  0  4  0  0
 0  0  0  0  0 13  0
 0  0  0  0  0  0  9

overall accuracy: 0.987805
Training time: 2746 seconds.
df.number_of_classes(): 7

Traceback (most recent call last):
  File "/usr/local/miniconda2/installation/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/miniconda2/installation/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/train.py", line 73, in <module>
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/train.py", line 66, in do_train
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/trainers/trainer.py", line 28, in train
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/trainers/mitie_trainer.py", line 22, in train_entity_extractor
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/trainers/mitie_trainer_utils.py", line 28, in train_entity_extractor
  File "build/bdist.macosx-10.7-x86_64/egg/rasa_nlu/trainers/mitie_trainer_utils.py", line 12, in find_entity
ValueError: <exception str() failed>

**Comment by tmbo** [comment]
@steookk This doesn't seem to be a german related issue but rather an issue with your training data, if you don't mind sending me your training data (tom@golastmile.com) I can help you with that error and maybe provide a better error message for the future.

**Comment by tmbo** [comment]
The value error should be fixed in the latest master version.

**Comment by steookk** [comment]
@tmbo sorry for not having been very responsive. I made some tries and found that the problem is having a space at the beginning of an entity.

Example
```json
      {
        "text": "Umsätze von heute und letzter Woche",
        "intent": "transactions",
        "entities": [
          {
            "start": 7,
            "end": 35,
            "value": " von heute und letzter Woche",
            "entity": "datetime"
          }
        ]
      }
```
 

Setting the start at 8 and removing the space at the beginning of the entity solved the problem

**Comment by tmbo** [comment]
Glad you found the issue. I improved the error message which should allow faster debugging of such training data issues.
