### ISSUE TITLE
Classifier has no predict(X) attribute while parsing

### ISSUE THREAD

**Issue by AndriiKr** [golastmile/rasa_nlu#201]
Hi! Thanks for new version implementation.
rasa NLU version (Don't know? https://goo.gl/g9QQg2):
latest version - __version__ = '0.7.0a5'

Used backend (`mitie`, `spacy_sklearn`, ...) & plattform (windows, osx, ...):
spacy_sklearn, Ubuntu 14.04, python 2.7

Issue: 

New python examples form doc not working for me.
Training working:
```
from rasa_nlu.training_data import TrainingData
from rasa_nlu.trainers.spacy_sklearn_trainer import SpacySklearnTrainer

nlpTrain = spacy.load('en', parser=False, entity=False) # load models
training_data = TrainingData(path, 'spacy_sklearn', nlpTrain, 'rasa_nlu')
trainer.train(training_data)
trainer.persist('./')
```
Parsing not working:
```
from rasa_nlu.interpreters.spacy_sklearn_interpreter import SpacySklearnInterpreter

metadata = json.loads(open('/path/to/metadata.json').read())
nlp = spacy.load("en", parser=False)
interpreters[bot_id] = SpacySklearnInterpreter(metadata, nlp=nlp)
interpreter = interpreters[request.args['bot_id']]
resp = interpreter.parse(request.json['q'])
```
Error:
```
[2017-03-06 18:48:06,428] ERROR in app: Exception on /parse [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)

  File "router_new.py", line 69, in parse
    resp = interpreter.parse(request.json['q'])

  File "build/bdist.linux-x86_64/egg/rasa_nlu/interpreters/spacy_sklearn_interpreter.py", line 76, in parse
    intent, probability = self.get_intent(doc)
  File "build/bdist.linux-x86_64/egg/rasa_nlu/interpreters/spacy_sklearn_interpreter.py", line 60, in get_intent
    intent_ids, probabilities = self.classifier.predict(X)
AttributeError: 'dict' object has no attribute 'predict'
```

**Comment by tmbo** [comment]
@AndriiKr good catch!

I did some refactoring and updated the example at https://rasa-nlu.readthedocs.io/en/latest/python.html#prediction-time

Let me know if there are any other issues
