### ISSUE TITLE
Mitie Installation Issue

### ISSUE THREAD

**Issue by parmeshashwath** [golastmile/rasa_nlu#202]
rasa NLU version (Don't know? https://goo.gl/g9QQg2):

Used backend (`mitie`, `spacy_sklearn`, ...) & plattform (windows, osx, ...):

Issue:
Not able to install mitie by following the instruction. Getting below error

Collecting git+https://github.com/mit-nlp/MITIE.git
  Cloning https://github.com/mit-nlp/MITIE.git to /tmp/pip-4TckCP-build
Installing collected packages: mitie
  Running setup.py install for mitie ... error
    Complete output from command /root/anaconda2/envs/python2.7/bin/python -u -c                                                                                                                      "import setuptools, tokenize;__file__='/tmp/pip-4TckCP-build/setup.py';f=getatt                                                                                                                     r(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close(                                                                                                                     );exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dYkI36-record                                                                                                                     /install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    make -C mitielib
    make[1]: Entering directory `/tmp/pip-4TckCP-build/mitielib'
    Compiling src/mitie.cpp
    make[1]: g++: Command not found
    make[1]: *** [src/mitie.o] Error 127
    make[1]: Leaving directory `/tmp/pip-4TckCP-build/mitielib'
    make: *** [mitielib] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-4TckCP-build/setup.py", line 33, in <module>
        'License :: Boost License',
      File "/root/anaconda2/envs/python2.7/lib/python2.7/distutils/core.py", lin                                                                                                                     e 151, in setup
        dist.run_commands()
      File "/root/anaconda2/envs/python2.7/lib/python2.7/distutils/dist.py", lin                                                                                                                     e 953, in run_commands
        self.run_command(cmd)
      File "/root/anaconda2/envs/python2.7/lib/python2.7/distutils/dist.py", lin                                                                                                                     e 972, in run_command
        cmd_obj.run()
      File "/root/anaconda2/envs/python2.7/lib/python2.7/site-packages/setuptool                                                                                                                     s-27.2.0-py2.7.egg/setuptools/command/install.py", line 61, in run
      File "/root/anaconda2/envs/python2.7/lib/python2.7/distutils/command/insta                                                                                                                     ll.py", line 563, in run
        self.run_command('build')
      File "/root/anaconda2/envs/python2.7/lib/python2.7/distutils/cmd.py", line                                                                                                                      326, in run_command
        self.distribution.run_command(command)
      File "/root/anaconda2/envs/python2.7/lib/python2.7/distutils/dist.py", lin                                                                                                                     e 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-4TckCP-build/setup.py", line 10, in run
        subprocess.check_call(['make', 'mitielib'])
      File "/root/anaconda2/envs/python2.7/lib/python2.7/subprocess.py", line 18                                                                                                                     6, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'mitielib']' returned non-z                                                                                                                     ero exit status 2

    ----------------------------------------
Command "/root/anaconda2/envs/python2.7/bin/python -u -c "import setuptools, tok                                                                                                                     enize;__file__='/tmp/pip-4TckCP-build/setup.py';f=getattr(tokenize, 'open', open                                                                                                                     )(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __f                                                                                                                     ile__, 'exec'))" install --record /tmp/pip-dYkI36-record/install-record.txt --si                                                                                                                     ngle-version-externally-managed --compile" failed with error code 1 in /tmp/pip-                                                                                                                     4TckCP-build/

**Comment by tmbo** [comment]
You should post that issue as a MITIE issue as it does not seem to be related to rasa NLU. They are probably able to help you with the setup. But feel free to post the solution here!

**Comment by rikhuijzer** [comment]
`g++: Command not found make[1]`

This means the 'suite of development tools' is missing (source: https://unix.stackexchange.com/questions/140350/linux-g-command-not-found). For Debian run `apt-get install build-essential`. For Alpine run `apk add build-base`.
