### ISSUE TITLE
Exception: Unable to load named entity extractor

### ISSUE THREAD

**Issue by getramki** [golastmile/rasa_nlu#203]
rasa NLU version: Latest - rasa-nlu (0.7.0a7)
Used backend: mitie_sklearn
plattform: ubuntu

Issue: While running server, getting error that "unable to load model_dir/entity_extractor.dat"
Training is working and model directory is getting created and enitty_extractor.dat file is also getting ceated.

Error loading MITIE model file: model_20170308-122617/entity_extractor.dat
This file does not contain a mitie::named_entity_extractor. Contained: mitie::named_entity_extractor_pure_model
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/rasa_nlu/server.py", line 99, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_nlu/server.py", line 90, in create_app
  File "build/bdist.linux-x86_64/egg/rasa_nlu/data_router.py", line 30, in __init__
  File "build/bdist.linux-x86_64/egg/rasa_nlu/data_router.py", line 101, in __create_model_store
  File "build/bdist.linux-x86_64/egg/rasa_nlu/data_router.py", line 154, in create_interpreter
  File "build/bdist.linux-x86_64/egg/rasa_nlu/interpreters/mitie_sklearn_interpreter.py", line 20, in load
  File "/usr/local/lib/python2.7/dist-packages/mitie/mitie.py", line 234, in __init__
    raise Exception("Unable to load named entity extractor from " + filename)
Exception: Unable to load named entity extractor from model_20170308-122617/entity_extractor.dat

**Comment by tmbo** [comment]
@getramki is this a model you trained with this version (0.7.0a7) or with a previous version? If you don't mind it would also be good if you could add the `metadata.json`.

**Comment by getramki** [comment]
Got Solved :) the problem was with my previous installation of mitie (0.2.0), I have upgraded it (may be minor patch) and now its working.

thanks @tmbo for the fast reply. It is trained with this version (0.7.0a7) only.

**Comment by tmbo** [comment]
Yes that is right. For future reference:

You need to install the latest version, since we are using so called pure models (where the feature extractor is not integrated into the model and can be loaded separately). This has been implement rather recently.
