### ISSUE TITLE
Spanish support

### ISSUE THREAD

**Issue by emartos** [golastmile/rasa_nlu#244]
rasa NLU version: 0.6b0
Used backend: `mitie`
Plattform: Ubuntu

Issue:

I am trying to make some tests with Spanish intents but I cannot make it work. Attending to the documentation of MITIE, it has Spanish support. I have downloaded the _total_word_feature_extractor.dat_ for Spanish and pointed to it in the configuration file:

```
{
  "backend": "mitie",
  "mitie_file": "./data/MITIE-models/spanish/total_word_feature_extractor.dat",
  "path" : "./",
  "data" : "./data/demo-rasa.default.json"
}

```
If I insert an intent with Spanish words, I get this error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/rasa_nlu/train.py", line 67, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_nlu/train.py", line 61, in do_train
  File "build/bdist.linux-x86_64/egg/rasa_nlu/trainers/mitie_trainer.py", line 31, in train
  File "build/bdist.linux-x86_64/egg/rasa_nlu/trainers/mitie_trainer.py", line 55, in train_entity_extractor
  File "build/bdist.linux-x86_64/egg/rasa_nlu/trainers/mitie_trainer.py", line 36, in find_entity
  File "build/bdist.linux-x86_64/egg/rasa_nlu/tokenizers/mitie_tokenizer.py", line 19, in tokenize_with_offsets
AttributeError: 'NoneType' object has no attribute 'start'
```

I have even tried to add the language to the configuration:

```
{
  "backend": "mitie",
  "language": "es",
  "mitie_file": "./data/MITIE-models/spanish/total_word_feature_extractor.dat",
  "path" : "./",
  "data" : "./data/demo-rasa.default.json"
}
```

But in this case I get this error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/rasa_nlu/train.py", line 66, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_nlu/train.py", line 51, in init
  File "build/bdist.linux-x86_64/egg/rasa_nlu/config.py", line 44, in __init__
  File "build/bdist.linux-x86_64/egg/rasa_nlu/config.py", line 82, in validate
ValueError: backend set to 'mitie' but language not set to 'en'.
```

I have read the _Installation_, _Configuration_ and _Language_ guides but I cannot find a solution.

**Comment by amn41** [comment]
Could you please update to the latest version and see if the problem persists?

**Comment by emartos** [comment]
Yes, sure! I'll try and post the results here.

**Comment by emartos** [comment]
Ok, I've installed the latest version from GitHub and followed the installation steps:

```
git clone git@github.com:golastmile/rasa_nlu.git
cd rasa_nlu
python setup.py install
```

I have placed the Spanish _total_word_feature_extractor.dat_, my _config.json_ file and the training model and executed the training, but it seem that no training is being done:

```
$ python -m rasa_nlu.train -c config.json
INFO:root:Successfully saved model into '/var/www/html/rasa_nlu2/model_20170331-114122'
INFO:root:done
```

Am I missing anything?

**Comment by tmbo** [comment]
Can you please share the contents of `config.json` as well?

**Comment by emartos** [comment]
**config.json**

```
{
  "backend": "mitie",
  "mitie_file": "./data/MITIE-models/spanish/total_word_feature_extractor.dat",
  "path" : "./",
  "data" : "./data/demo-rasa.default.json"
}
```

**./data/demo-rasa.default.json**

**Note:** You can see that there are only two examples in Spanish at the end of each section.

```
{
  "rasa_nlu_data": {
    "entity_examples": [
      {
        "text": "hey", 
        "intent": "greet", 
        "entities": []
      }, 
      {
        "text": "howdy", 
        "intent": "greet", 
        "entities": []
      }, 
      {
        "text": "hey there", 
        "intent": "greet", 
        "entities": []
      }, 
      {
        "text": "hello", 
        "intent": "greet", 
        "entities": []
      }, 
      {
        "text": "hi", 
        "intent": "greet", 
        "entities": []
      }, 
      {
        "text": "i'm looking for a place to eat", 
        "intent": "restaurant_search", 
        "entities": []
      }, 
      {
        "text": "i'm looking for a place in the north of town", 
        "intent": "restaurant_search", 
        "entities": [
          {
            "start": 31,
            "end": 36, 
            "value": "north", 
            "entity": "location"
          }
        ]
      }, 
      {
        "text": "show me chinese restaurants", 
        "intent": "restaurant_search", 
        "entities": [
          {
            "start": 8, 
            "end": 15, 
            "value": "chinese", 
            "entity": "cuisine"
          }
        ]
      }, 
      {
        "text": "yes", 
        "intent": "affirm", 
        "entities": []
      }, 
      {
        "text": "yep", 
        "intent": "affirm", 
        "entities": []
      }, 
      {
        "text": "yeah", 
        "intent": "affirm", 
        "entities": []
      }, 
      {
        "text": "show me a mexican place in the centre", 
        "intent": "restaurant_search", 
        "entities": [
          {
            "start": 31, 
            "end": 37, 
            "value": "centre", 
            "entity": "location"
          }, 
          {
            "start": 10, 
            "end": 17, 
            "value": "mexican", 
            "entity": "cuisine"
          }
        ]
      }, 
      {
        "text": "bye", 
        "intent": "goodbye", 
        "entities": []
      }, 
      {
        "text": "goodbye", 
        "intent": "goodbye", 
        "entities": []
      }, 
      {
        "text": "good bye", 
        "intent": "goodbye", 
        "entities": []
      }, 
      {
        "text": "stop", 
        "intent": "goodbye", 
        "entities": []
      }, 
      {
        "text": "end", 
        "intent": "goodbye", 
        "entities": []
      }, 
      {
        "text": "i am looking for an indian spot", 
        "intent": "restaurant_search", 
        "entities": [ 
          {
            "start": 20, 
            "end": 26, 
            "value": "indian",
            "entity": "cuisine"
          }
        ]
      }, 
      {
        "text": "search for restaurants", 
        "intent": "restaurant_search", 
        "entities": []
      }, 
      {
        "text": "anywhere in the west", 
        "intent": "restaurant_search", 
        "entities": [
          {
            "start": 16, 
            "end": 20, 
            "value": "west", 
            "entity": "location"
          }
        ]
      }, 
      {
        "text": "central indian restaurant", 
        "intent": "restaurant_search", 
        "entities": [
          {
            "start": 0, 
            "end": 7, 
            "value": "central", 
            "entity": "location"
          }, 
          {
            "start": 8, 
            "end": 14, 
            "value": "indian",
            "entity": "cuisine"
          }
        ]
      },
      {
        "text": "estoy buscando información sobre vuestros proyectos",
        "intent": "info_request",
        "entities": [
          {
            "start": 0,
            "end": 5,
            "value": "proyectos",
            "entity": "proyectos"
          }
        ]
      }, 
      {
        "text": "dame información sobre vuestros proyectos",
        "intent": "info_request",
        "entities": [
          {
            "start": 0,
            "end": 5,
            "value": "proyectos",
            "entity": "proyectos"
          }
        ]
      },
      {
        "text": "indeed", 
        "intent": "affirm", 
        "entities": []
      }, 
      {
        "text": "that's right", 
        "intent": "affirm", 
        "entities": []
      }, 
      {
        "text": "ok", 
        "intent": "affirm", 
        "entities": []
      }, 
      {
        "text": "great", 
        "intent": "affirm", 
        "entities": []
      }
    ], 
    "intent_examples": [
      {
        "text": "hey", 
        "intent": "greet"
      }, 
      {
        "text": "howdy", 
        "intent": "greet"
      }, 
      {
        "text": "hey there", 
        "intent": "greet"
      }, 
      {
        "text": "hello", 
        "intent": "greet"
      }, 
      {
        "text": "hi", 
        "intent": "greet"
      }, 
      {
        "text": "i'm looking for a place to eat", 
        "intent": "restaurant_search"
      }, 
      {
        "text": "i'm looking for a place in the north of town", 
        "intent": "restaurant_search"
      }, 
      {
        "text": "show me chinese restaurants", 
        "intent": "restaurant_search"
      }, 
      {
        "text": "yes", 
        "intent": "affirm"
      }, 
      {
        "text": "yep", 
        "intent": "affirm"
      }, 
      {
        "text": "yeah", 
        "intent": "affirm"
      }, 
      {
        "text": "show me a mexican place in the centre", 
        "intent": "restaurant_search"
      }, 
      {
        "text": "bye", 
        "intent": "goodbye"
      }, 
      {
        "text": "goodbye", 
        "intent": "goodbye"
      }, 
      {
        "text": "good bye", 
        "intent": "goodbye"
      }, 
      {
        "text": "stop", 
        "intent": "goodbye"
      }, 
      {
        "text": "end", 
        "intent": "goodbye"
      }, 
      {
        "text": "i am looking for an indian spot", 
        "intent": "restaurant_search"
      }, 
      {
        "text": "search for restaurants", 
        "intent": "restaurant_search"
      }, 
      {
        "text": "anywhere in the west", 
        "intent": "restaurant_search"
      }, 
      {
        "text": "central indian restaurant", 
        "intent": "restaurant_search"
      }, 
      {
        "text": "indeed", 
        "intent": "affirm"
      }, 
      {
        "text": "that's right", 
        "intent": "affirm"
      }, 
      {
        "text": "ok", 
        "intent": "affirm"
      }, 
      {
        "text": "great", 
        "intent": "affirm"
      },
      {
        "text": "estoy buscando información sobre vuestros proyectos",
        "intent": "info_request"
      },
      {
        "text": "dame información sobre vuestros proyectos",
        "intent": "info_request"
      }
    ]
  }
}
```

**Comment by tmbo** [comment]
ok first thing: after updating to master `backend` in your config should become `pipeline`

**Comment by tmbo** [comment]
also, you should specify your language if you are not using english

**Comment by emartos** [comment]
Ok, I have updated with **git pull** (**master** branch) and changed my config.json:

{
  "backend": "pipeline",
  "language": "es",
  "mitie_file": "./data/MITIE-models/spanish/total_word_feature_extractor.dat",
  "path" : "./",
  "data" : "./data/demo-rasa.default.json"
}

When I execute the training, I get a new error:

```
$ python -m rasa_nlu.train -c config.json
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/www/html/rasa_nlu2/rasa_nlu/train.py", line 9, in <module>
    from rasa_nlu.converters import load_data
  File "rasa_nlu/converters.py", line 13, in <module>
    from rasa_nlu.tokenizers import Tokenizer
  File "rasa_nlu/tokenizers/__init__.py", line 5, in <module>
    from builtins import object
ImportError: No module named builtins

```

It's the first news I got about **pipeline**. Where can I find documentation about that?

**Comment by tmbo** [comment]
You can find more information in the latest documentation:
https://rasa-nlu.readthedocs.io/en/latest/changelog.html

Your backend / pipeline config is wrong. Remove the backend key and add `"pipeline": "mitie"`.

Also make sure to run `pip install -r requirements.txt`. Please also have a look at your numpy version, should be at least 1.12.

**Comment by emartos** [comment]
Yeah, it's working now! First of all, sorry for my obvious mistakes (I'm just starting and learning), and thank you so much for your great support!

If anyone else needs help configuring Spanish language, I will be happy to help.
