### ISSUE TITLE
rasa_nlu.server - TypeError: loop() got an unexpected keyword argument 'default'

### ISSUE THREAD

**Issue by kmccurdy** [golastmile/rasa_nlu#250]
**rasa NLU version**: 0.8.0a4

**Used backend / pipeline**: ["init_mitie", "tokenizer_mitie", "ner_mitie", "ner_synonyms"]

**Operating system**: OSX

**Issue**:
Trying to start a server from a trained model, all libraries etc up to date, and it consistently throws this error:
```
INFO:root:Loading model 'model_20170403-101559'...
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/dev/parsa/rasa_nlu/server.py", line 105, in <module>
    app = WSGIServer(('0.0.0.0', rasa_nlu_config['port']), create_app(rasa_nlu_config))
  File "/anaconda/lib/python2.7/site-packages/gevent/pywsgi.py", line 1406, in __init__
    StreamServer.__init__(self, listener, backlog=backlog, spawn=spawn, **ssl_args)
  File "/anaconda/lib/python2.7/site-packages/gevent/server.py", line 90, in __init__
    BaseServer.__init__(self, listener, handle=handle, spawn=spawn)
  File "/anaconda/lib/python2.7/site-packages/gevent/baseserver.py", line 95, in __init__
    self._stop_event = Event()
  File "/anaconda/lib/python2.7/site-packages/gevent/event.py", line 32, in __init__
    self.hub = get_hub()
  File "/anaconda/lib/python2.7/site-packages/gevent/hub.py", line 371, in get_hub
    hub = _threadlocal.hub = hubtype(*args, **kwargs)
  File "/anaconda/lib/python2.7/site-packages/gevent/hub.py", line 518, in __init__
    self.loop = loop_class(flags=loop, default=default)
  File "core.pyx", line 402, in gevent.core.loop (gevent/core.c:6195)
TypeError: loop() got an unexpected keyword argument 'default'

```

**Content of configuration file** (if used & relevant):
```json
{
  "pipeline": ["init_mitie", "tokenizer_mitie", "ner_mitie", "ner_synonyms"],
  "language": "en",
  "mitie_file": "./MITIE-models/english/total_word_feature_extractor.dat",
  "path" : "models",
  "data" : "data",
  "server_model_dirs": {
    "model": "model_20170403-101559"
  }
}
```

**Comment by kmccurdy** [comment]
this seems relevant: https://github.com/locustio/locust/issues/485

but I've got gevent version 1.2.1 ¯\_(ツ)_/¯

**Comment by tmbo** [comment]
I can not reproduce this with the current master. If this is still an issue for you, please post the command you are using to run the server.
