### ISSUE TITLE
Getting AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by shahbazahmed1269** [golastmile/rasa_nlu#263]
**rasa NLU version**: 0.8.0a5 (cloned today from latest master branch)

**Used backend / pipeline**: Mitie pipeline

**Operating system** (windows, osx, ...): osx

**Issue**: I get the below error when i try to start the server  by executing `-m rasa_nlu.server -c config.json --server_model_dirs=./model_20170405-151522 `

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/shahbaz/Documents/tincan-cloud/rasa_nlu/rasa_nlu/rasa_nlu/server.py", line 105, in <module>
    app = WSGIServer(('0.0.0.0', rasa_nlu_config['port']), create_app(rasa_nlu_config))
  File "/Users/shahbaz/Documents/tc-cloud/rasa_nlu/rasa_nlu/rasa_nlu/server.py", line 96, in create_app
    rasa_nlu_app.data_router = DataRouter(config)
  File "rasa_nlu/data_router.py", line 72, in __init__
    self.model_store = self.__create_model_store()
  File "rasa_nlu/data_router.py", line 121, in __create_model_store
    for alias, model_path in list(model_dict.items()):
AttributeError: 'str' object has no attribute 'items'

I took a look into recent commits and I think the issue may be because of the following commit: [link](https://github.com/golastmile/rasa_nlu/commit/cca505eff0f78a9ed730f9e8f54e7f4a2b641573#diff-3d59f7434f7aad5d198e011666f2c170)

**Comment by tmbo** [comment]
@shahbazahmed1269 thanks for the report, let me have a look at that.

**Comment by shahbazahmed1269** [comment]
@tmbo If it may help, I have created a pull request (PR #264)  on how I fixed the above error.
