### ISSUE TITLE
Train successful but Curl result - No json object could be decoded

### ISSUE THREAD

**Issue by HardikShah289** [golastmile/rasa_nlu#271]
**rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie_sklearn`, ...):

**Operating system** (windows, ):

**Issue**:
I have successfully train with mitie_sklearn config. Now, when i tried to test through CURL getting 
No JSON object could be decoded for every request.

I have attached the config file, train result, call status, & response on Curl window.

Please help me to understand where I have made mistake.
[AfterTrainingResponse.txt](https://github.com/golastmile/rasa_nlu/files/905388/AfterTrainingResponse.txt)
[Train Log Successful.txt](https://github.com/golastmile/rasa_nlu/files/905387/Train.Log.Successful.txt)

**Content of configuration file** (if used & relevant):
```json

```

**Comment by tmbo** [comment]
What is the result of hitting `localhost:5000/parse?q=I want some italian` with your browser?

**Comment by HardikShah289** [comment]
This is what exception i have received while hitting with browser.

[2017-04-10 13:14:59,232] ERROR in app: Exception on /parse [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch
_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_e
xception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch
_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_requ
est
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\rasa_nlu-master\rasa_nlu\server.py", line 48, in decorated
    return f(*args, **kwargs)
  File "C:\rasa_nlu-master\rasa_nlu\server.py", line 69, in parse_get
    response = current_app.data_router.parse(data)
  File "rasa_nlu\data_router.py", line 187, in parse
    response = model.parse(data['text'])
  File "rasa_nlu\model.py", line 266, in parse
    updates = component.process(*args)
  File "rasa_nlu\classifiers\sklearn_intent_classifier.py", line 85, in process
    intent_ids, probabilities = self.predict(X)
  File "rasa_nlu\classifiers\sklearn_intent_classifier.py", line 122, in predict

    sorted_indices = np.flip(np.argsort(pred_result, axis=1), axis=1)
AttributeError: 'module' object has no attribute 'flip'
127.0.0.1 - - [2017-04-10 13:14:59] "GET /parse?q=I%20want%20some%20italina HTTP
/1.1" 500 412 0.078000
[2017-04-10 13:15:18,684] ERROR in app: Exception on /parse [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch
_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_e
xception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch
_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_requ
est
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\rasa_nlu-master\rasa_nlu\server.py", line 48, in decorated
    return f(*args, **kwargs)
  File "C:\rasa_nlu-master\rasa_nlu\server.py", line 69, in parse_get
    response = current_app.data_router.parse(data)
  File "rasa_nlu\data_router.py", line 187, in parse
    response = model.parse(data['text'])
  File "rasa_nlu\model.py", line 266, in parse
    updates = component.process(*args)
  File "rasa_nlu\classifiers\sklearn_intent_classifier.py", line 85, in process
    intent_ids, probabilities = self.predict(X)
  File "rasa_nlu\classifiers\sklearn_intent_classifier.py", line 122, in predict

    sorted_indices = np.flip(np.argsort(pred_result, axis=1), axis=1)
AttributeError: 'module' object has no attribute 'flip'
127.0.0.1 - - [2017-04-10 13:15:18] "GET /parse?q=I%20want%20some%20italian HTTP
/1.1" 500 412 0.000000
127.0.0.1 - - [2017-04-10 13:34:09] "POST /parse HTTP/1.1" 400 303 0.000000

**Comment by tmbo** [comment]
@HardikShah289 please make sure you are running the latest version of `numpy`. The code requires a version `>=v1.12`

**Comment by HardikShah289** [comment]
i run below code in python.

import numpy
numpy.version.version

output: 1.12.1

**Comment by tmbo** [comment]
It's probably an issue with your environment, the code you posted above is probably executed using either a different python or a different package import path. I am quite certain that the above error is a result of a non 1.12 numpy version.

**Comment by HardikShah289** [comment]
I think, you are right. it might due to wrong numpy+mkl version issue. Right now, it is working with spacy config..

**Comment by tmbo** [comment]
I'll close this for now, as I don't think this is an issue in the framework. But let me know if you think there is something going wrong.

**Comment by abhi31991** [comment]
Hi tmbo,
Operating system (windows, ):
Issue:
I am using this query to get result from Bot " curl -X POST "localhost:5000/parse" -d "{/"q/":/"I want some italian/"}" | python -m json.tool ", using cmd prompt.

Result : 
No JSON object could be decoded for every request.

In Browser : ( localhost:5000/parse?q=I want some italian ) I am getting this result.
{
  "entities": [], 
  "intent": {
    "confidence": 0.5412828827537383, 
    "name": "restaurant_search"
  }, 
  "text": "I want some italian", 
  "intent_ranking": [
    {
      "confidence": 0.5412828827537383, 
      "name": "restaurant_search"
    }, 
    {
      "confidence": 0.29342213996129496, 
      "name": "affirm"
    }, 
    {
      "confidence": 0.08801529057559661, 
      "name": "greet"
    }, 
    {
      "confidence": 0.07727968670937009, 
      "name": "goodbye"
    }
  ]
}
What is issue can you please explain me ?. Why i am getting error in cmd.

**Comment by wrathagom** [comment]
@abhi31991 please create a new issue and include any stack trace errors that appear in the console. My guess is that it may be a core issue?
