### ISSUE TITLE
Prediction Error from Sklearn classifier module

### ISSUE THREAD

**Issue by sourjatilak** [golastmile/rasa_nlu#279]
**rasa NLU version** (e.g. `0.7.3`): 0.8.0a10

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):  ["nlp_mitie", "tokenizer_mitie", "ner_mitie","ner_duckling","ner_synonyms","intent_featurizer_mitie", "intent_classifier_keyword","intent_classifier_sklearn"]

**Operating system** (windows, osx, ...): Mac OSX 10.11.6

**Issue**: 
 The model got trained properly. After running the server and quering, I am getting the below error:

INFO:root:Started http server on port 5000
[2017-04-17 16:31:21,339] ERROR in app: Exception on /parse [POST]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sourjabanerjee/Documents/rasa/rasa_nlu/rasa_nlu/server.py", line 48, in decorated
    return f(*args, **kwargs)
  File "/Users/sourjabanerjee/Documents/rasa/rasa_nlu/rasa_nlu/server.py", line 69, in parse_get
    response = current_app.data_router.parse(data)
  File "rasa_nlu/data_router.py", line 150, in parse
    response = model.parse(data['text'])
  File "rasa_nlu/model.py", line 285, in parse
    updates = component.process(*args)
  File "rasa_nlu/classifiers/sklearn_intent_classifier.py", line 97, in process
    intent_ids, probabilities = self.predict(X)
  File "rasa_nlu/classifiers/sklearn_intent_classifier.py", line 133, in predict
    sorted_indices = np.flip(np.argsort(pred_result, axis=1), axis=1)
AttributeError: 'module' object has no attribute 'flip'
127.0.0.1 - - [2017-04-17 16:31:21] "POST /parse HTTP/1.1" 500 412 0.025745

**Comment by tmbo** [comment]
You need at least numpy version `1.12`. 

We should really think about removing the flip and replacing it with backwards compatible numpy code. @twerkmeister can you have a look at that?
