### ISSUE TITLE
Cannot load models with spacy 1.8

### ISSUE THREAD

**Issue by willemchua** [golastmile/rasa_nlu#282]
rasa NLU version : 0.8.0a10

Used backend / pipeline: "spacy_sklearn"

Operating system (windows, osx, ...): tried in Windows 8.1 and mac OS X

Issue:
I was using the latest version of Rasa NLU and was able to train a model using the configuration and example data given by the docs. However, when I tried to run the trained model using this command 

`python -m rasa_nlu.server -c config_spacy.json --server_model_dirs=./model_YYYYMMDD-HHMMSS`

it gave out this error message, though the server still ran with the default output ('greet' with confidence 1):
```
ERROR:root:Failed to load model './model_20170418-162706'. Error: 'actions'
Traceback (most recent call last):

  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\rasa_nlu\data_router.py", line 84, in __create_model_store
    interpreter = Interpreter.load(metadata, self.config, self.component_builder)

  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\rasa_nlu\model.py", line 249, in load
    component = component_builder.load_component(component_name, context, model_config, meta)

  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\rasa_nlu\components.py", line 234, in load_component
    component = registry.load_component_by_name(component_name, context, model_config)

  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\rasa_nlu\registry.py", line 89, in load_component_by_name
    return load_component(component_clz, context, config)

  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\rasa_nlu\components.py", line 27, in load_component
    return component_clz.load(*load_args)

  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\rasa_nlu\extractors\spacy_entity_extractor.py", line 103, in load
    ner = EntityRecognizer.load(pathlib.Path(ner_dir), spacy_nlp.vocab)

  File "spacy/syntax/parser.pyx", line 149, in spacy.syntax.parser.Parser.load (spacy/syntax/parser.cpp:6845)

KeyError: 'actions'
INFO:root:Started http server on port 5000
```

**Comment by tmbo** [comment]
Which version of spacy are you using?

**Comment by willemchua** [comment]
@tmbo I'm using spacy 1.8.0

**Comment by tmbo** [comment]
We haven't ported / tested 1.8 yet. Might be an issue with the move from 1.7 to 1.8. I'll create a separate issue for that. In the meantime you could try installing 1.7.x

**Comment by tmbo** [comment]
Ok, I verified it is an issue with the update to spacy 1.8.0. I'll have a look at it, but in the meantime you can downgrade to 1.7 using `pip install -U spacy==1.7.5`

**Comment by tmbo** [comment]
This is an issue on the spacy part and I haven't found a way to get around this yet. https://github.com/explosion/spaCy/issues/999

**Comment by tmbo** [comment]
I'll close this in favor of #284. In the meantime, don't use spacy 1.8
