### ISSUE TITLE
unable to start rasa_nlu server

### ISSUE THREAD

**Issue by vibhutibindal** [golastmile/rasa_nlu#294]
**rasa NLU version** (e.g. `0.7.3`):0.7.4

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):spacy_sklearn

**Operating system** (windows, osx, ...):windows

**Issue**:

**Content of configuration file** (if used & relevant):
```json

```
i am unable to start rasa nlu server with python 2.7 64 bit.I am getting this error

C:\Users\BINVI01\PycharmProjects\rasa_nlu>python -m rasa_nlu.train -c config.jso
n

C:\Users\BINVI01\PycharmProjects\rasa_nlu>python -m rasa_nlu.server -c config.js
on --server_model_dirs=./model_20170420-190910
INFO:root:Configuration: {
    "num_threads": 1,
    "log_level": 20,
    "language": "en",
    "mitie_file": "data\\total_word_feature_extractor.dat",
    "emulate": null,
    "config": "config.json",
    "response_log": "C:\\Users\\BINVI01\\PycharmProjects\\rasa_nlu\\logs",
    "server_model_dirs": "./model_20170420-190910",
    "fine_tune_spacy_ner": false,
    "token": null,
    "path": "./models",
    "log_file": null,
    "data": "./data/test.json",
    "port": 5000,
    "backend": "spacy_sklearn"
}
INFO:root:Logging requests to 'C:\Users\BINVI01\PycharmProjects\rasa_nlu\logs\rasa_nlu_log-20170420-191010-16152.log'.
INFO:root:using spacy + sklearn backend
Traceback (most recent call last):
  File "C:\Python2764\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python2764\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python2764\lib\site-packages\rasa_nlu\server.py", line 99, in <module
>
    app = WSGIServer(('0.0.0.0', rasa_nlu_config['port']), create_app(rasa_nlu_c
onfig))
  File "C:\Python2764\lib\site-packages\rasa_nlu\server.py", line 90, in create_
app
    rasa_nlu_app.data_router = DataRouter(config)
  File "C:\Python2764\lib\site-packages\rasa_nlu\data_router.py", line 29, in __
init__
    self.model_store = self.__create_model_store()
  File "C:\Python2764\lib\site-packages\rasa_nlu\data_router.py", line 112, in _
_create_model_store
    interpreter = DataRouter.create_interpreter(metadata, nlp, featurizer)
  File "C:\Python2764\lib\site-packages\rasa_nlu\data_router.py", line 170, in c
reate_interpreter
    return SpacySklearnInterpreter.load(metadata, nlp, featurizer)
  File "C:\Python2764\lib\site-packages\rasa_nlu\interpreters\spacy_sklearn_inte
rpreter.py", line 25, in load
    meta.metadata.get("should_fine_tune_spacy_ner"))
  File "C:\Python2764\lib\site-packages\rasa_nlu\extractors\spacy_entity_extract
or.py", line 15, in __init__
    self.ner = EntityRecognizer.load(pathlib.Path(extractor_file), nlp.vocab)
  File "spacy/syntax/parser.pyx", line 149, in spacy.syntax.parser.Parser.load (
spacy/syntax/parser.cpp:6845)
    for action_name, labels in dict(cfg['actions']).items():
KeyError: u'actions'

C:\Users\BINVI01\PycharmProjects\rasa_nlu>

**Comment by tmbo** [comment]
duplicates #282 gist: downgrade to spacy 1.7
