### ISSUE TITLE
unable to start rasa_nlu.server with Spacy 1.7.3 and Rasa 0.8.0a11

### ISSUE THREAD

**Issue by znat** [golastmile/rasa_nlu#306]
I downgraded spacy to 1.7.3 and got the following error:

```
INFO:root:Logging requests to '/Users/nzylber1/git/rasa.test.project/logs/rasa_nlu_log-20170425-171654-86789.log'.
INFO:root:Loading model './model_20170425-165508'...
INFO:root:Trying to load spacy model with name 'en'
INFO:root:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
ERROR:root:Failed to load model './model_20170425-165508'. Error: 1
Traceback (most recent call last):
  File "build/bdist.macosx-10.9-x86_64/egg/rasa_nlu/data_router.py", line 84, in __create_model_store
    interpreter = Interpreter.load(metadata, self.config, self.component_builder)
  File "build/bdist.macosx-10.9-x86_64/egg/rasa_nlu/model.py", line 213, in load
    component = component_builder.load_component(component_name, context, model_config, meta)
  File "build/bdist.macosx-10.9-x86_64/egg/rasa_nlu/components.py", line 339, in load_component
    component = registry.load_component_by_name(component_name, context, model_config)
  File "build/bdist.macosx-10.9-x86_64/egg/rasa_nlu/registry.py", line 89, in load_component_by_name
    return load_component(component_clz, context, config)
  File "build/bdist.macosx-10.9-x86_64/egg/rasa_nlu/components.py", line 30, in load_component
    return component_clz.load(*load_args)
  File "build/bdist.macosx-10.9-x86_64/egg/rasa_nlu/extractors/spacy_entity_extractor.py", line 108, in load
    ner = EntityRecognizer.load(pathlib.Path(ner_dir), spacy_nlp.vocab)
  File "spacy/syntax/parser.pyx", line 155, in spacy.syntax.parser.Parser.load (spacy/syntax/parser.cpp:6847)
    self = cls(vocab, TransitionSystem=TransitionSystem, model=None, **cfg)
  File "spacy/syntax/parser.pyx", line 177, in spacy.syntax.parser.Parser.__init__ (spacy/syntax/parser.cpp:7214)
    actions = TransitionSystem.get_actions(**cfg)
  File "spacy/syntax/ner.pyx", line 66, in spacy.syntax.ner.BiluoPushDown.get_actions (spacy/syntax/ner.cpp:3810)
    actions[action][entity_type] = True
KeyError: 1
```

Config file:
```
{
  "pipeline": "spacy_sklearn",
  "path" : "./models",
  "data" : "./demo_data.json" // demo data from Rasa tutorial
}
```

**Comment by tmbo** [comment]
@znat version 0.7.x does not support spacy 1.7.x (unfortunately the spacy guys introduced breaking changes in a minor version change...). either use 1.6 or use rasa NLU master and go with 1.7

spacy 1.8 is not yet supported either (another breaking release...)

@twerkmeister this should be added to the install guide for 0.8

**Comment by znat** [comment]
@tmbo , made a mistake : I am using rasa 0.8.0a11 (pulled from master) and spacy 1.7.3
