### ISSUE TITLE
Error during prediction using trained CRF model

### ISSUE THREAD

**Issue by xliuhw** [golastmile/rasa_nlu#337]
**rasa NLU version** Latest 0.8.0a15

**Used pipeline** ["nlp_spacy", "intent_featurizer_spacy", "tokenizer_mitie", "intent_classifier_sklearn", "ner_crf"],

**Operating system** Ubuntu 14 and 16

**Issue**:
After I trained model with sklearn+crf, I got error during the prediction tests after about 500 successful query:

query:1 = write an email to my family saying i love you all
Traceback (most recent call last):
  File "queryRasaLatest.py", line 141, in <module>
    main(sys.argv[1:])
  File "queryRasaLatest.py", line 110, in main
    res = interpreter.parse(utt)
  File "build/bdist.linux-x86_64/egg/rasa_nlu/model.py", line 258, in parse
  File "build/bdist.linux-x86_64/egg/rasa_nlu/extractors/crf_entity_extractor.py", line 94, in process
  File "build/bdist.linux-x86_64/egg/rasa_nlu/extractors/crf_entity_extractor.py", line 114, in extract_entities
  File "build/bdist.linux-x86_64/egg/rasa_nlu/extractors/crf_entity_extractor.py", line 138, in _from_crf_to_json
IndexError: list index out of range

What could be the cause for this?

Thanks!

```json

```

**Comment by tmbo** [comment]
This seems to be a bug in the extractor for a specific example. If you don't mind, it would be really helpful and speed up fixing this if you could send us the training data (tom@golastmile.com) and the example that caused the error.

**Comment by xliuhw** [comment]
Okay, I will send the relevant data soon.

It looks like it accumulates something during the prediction. It works fine when I call the interpreter with the utterance which caused error earlier, but when looping over all test sentences I got that error.

**Comment by tmbo** [comment]
Alright, in that case it might be good if you could include them in your mail as well.

**Comment by xliuhw** [comment]
Yes, have sent over.

**Comment by tmbo** [comment]
Alright, I can successfully load your model. What do I need to do to reproduce the error?

**Comment by xliuhw** [comment]
sent you a script for reproduce the error.

**Comment by xliuhw** [comment]
Further information: 
I got this error after I have called 964 times of res = interpreter.parse(utt)

  File "build/bdist.linux-x86_64/egg/rasa_nlu/model.py", line 258, in parse
  File "build/bdist.linux-x86_64/egg/rasa_nlu/extractors/crf_entity_extractor.py", line 94, in process
  File "build/bdist.linux-x86_64/egg/rasa_nlu/extractors/crf_entity_extractor.py", line 114, in extract_entities
  File "build/bdist.linux-x86_64/egg/rasa_nlu/extractors/crf_entity_extractor.py", line 138, in _from_crf_to_json
IndexError: list index out of range

**Comment by tmbo** [comment]
Alright, @xliuhw I just pushed a fix for that. I can run the script you send me without any issues now. Let me know if you still encounter any issues.

**Comment by xliuhw** [comment]
Yes, now it is working as expected! Thanks! I close this post now.
