### ISSUE TITLE
Is MITIE mandatory to run rasa ?

### ISSUE THREAD

**Issue by srijiths** [golastmile/rasa_nlu#341]
I installed rasa, spacy and sklearn. When i try to build a model below configuration generating exception as mitie module not found. From the docs i understand that rasa can work with any backend as per our choice. Is that correct ?

```
{
  "pipeline": "spacy_sklearn",
  "path" : "./models",
  "data" : "./data/sentiment/sentiment-data.json"
}
```
Exception is
````
python -m rasa_nlu.train -c sentiment-config.json
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/rasa_nlu/train.py", line 72, in <module>
    do_train(config)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/rasa_nlu/train.py", line 60, in do_train
    trainer = create_trainer(config)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/rasa_nlu/train.py", line 29, in create_trainer
    from trainers.mitie_trainer import MITIETrainer
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/rasa_nlu/trainers/mitie_trainer.py", line 4, in <module>
    from mitie import *
ImportError: No module named mitie

````
Its hitting rasa_nlu/train.py but why its looking for mittie ?

````
def create_trainer(config):
    backend = config.backend.lower()
    if backend == 'mitie':
        from trainers.mitie_trainer import MITIETrainer
        return MITIETrainer(config.mitie_file, config.language, config.num_threads)
````

**Comment by srijiths** [comment]
But when i changed the configuration from "pipeline": "spacy_sklearn", to "backend": "spacy_sklearn", its creating the model with these comemnts

```
/home/ubuntu/anaconda2/lib/python2.7/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/ubuntu/anaconda2/lib/python2.7/site-packages/sklearn/metrics/classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
```

When i deploy it , getting exceptions like ,
```
INFO:root:Configuration: {
    "num_threads": 1,
    "log_level": 20,
    "language": "en",
    "mitie_file": "data/total_word_feature_extractor.dat",
    "emulate": null,
    "config": "sentiment-config.json",
    "response_log": "/home/ubuntu/sree/rasa/logs",
    "server_model_dirs": "./model_20170508-122907",
    "fine_tune_spacy_ner": false,
    "token": null,
    "path": "./models",
    "log_file": null,
    "data": "./data/sentiment/sentiment-data.json",
    "port": 5000,
    "backend": "spacy_sklearn"
}
INFO:root:Logging requests to '/home/ubuntu/sree/rasa/logs/rasa_nlu_log-20170508-123854-5311.log'.
INFO:root:using spacy + sklearn backend
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/rasa_nlu/server.py", line 99, in <module>
    app = WSGIServer(('0.0.0.0', rasa_nlu_config['port']), create_app(rasa_nlu_config))
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/rasa_nlu/server.py", line 90, in create_app
    rasa_nlu_app.data_router = DataRouter(config)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/rasa_nlu/data_router.py", line 29, in __init__
    self.model_store = self.__create_model_store()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/rasa_nlu/data_router.py", line 112, in __create_model_store
    interpreter = DataRouter.create_interpreter(metadata, nlp, featurizer)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/rasa_nlu/data_router.py", line 170, in create_interpreter
    return SpacySklearnInterpreter.load(metadata, nlp, featurizer)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/rasa_nlu/interpreters/spacy_sklearn_interpreter.py", line 25, in load
    meta.metadata.get("should_fine_tune_spacy_ner"))
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/rasa_nlu/extractors/spacy_entity_extractor.py", line 15, in __init__
    self.ner = EntityRecognizer.load(pathlib.Path(extractor_file), nlp.vocab)
  File "spacy/syntax/parser.pyx", line 154, in spacy.syntax.parser.Parser.load (spacy/syntax/parser.cpp:6999)
  File "spacy/syntax/parser.pyx", line 177, in spacy.syntax.parser.Parser.__init__ (spacy/syntax/parser.cpp:7370)
  File "spacy/syntax/ner.pyx", line 71, in spacy.syntax.ner.BiluoPushDown.get_actions (spacy/syntax/ner.cpp:3906)
KeyError: 1

```

**Comment by twerkmeister** [comment]
Hi @srijiths, would you mind sharing which rasa nlu version you are using? We fixed the dependency on unused modules recently, so your problem should be gone in the current version and on master.

**Comment by tmbo** [comment]
this isn't relevant anymore due to the removal of spacy ner training ;) in the just released version.

**Comment by tmbo** [comment]
@srijiths there will be a newly released version on pypi in a couple of minutes, please update to that one if possible. it should resolve your issue.

**Comment by srijiths** [comment]
@tmbo @twerkmeister Thanks . I upgraded rasa version to rasa_nlu-0.8.0.tar.gz and its working perfectly. I am able to create model and successfully deploy it.
