### ISSUE TITLE
ner_duckling unicode issue during persistence

### ISSUE THREAD

**Issue by ecomaven** [golastmile/rasa_nlu#358]
**rasa NLU version**: 0.8.4

**Used backend / pipeline**: [ "nlp_mitie", "tokenizer_mitie", "ner_mitie", "ner_synonyms", "ner_duckling", "intent_featurizer_mitie", "intent_classifier_sklearn" ]

**Issue**:
When trying to train a dataset using the above pipeline, the following error is generated

```
INFO:root:Finished training component.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/vagrant/devFolder/rasa-nlu-env/src/rasa_nlu/rasa_nlu/train.py", line 83, in <module>
    do_train(config)
  File "/vagrant/devFolder/rasa-nlu-env/src/rasa_nlu/rasa_nlu/train.py", line 74, in do_train
    persisted_path = trainer.persist(config['path'], persistor, model_name=config['name'])
  File "rasa_nlu/model.py", line 183, in persist
    update = component.persist(dir_name)
  File "rasa_nlu/extractors/duckling_extractor.py", line 104, in persist
    f.write(json.dumps({"dimensions": self.dimensions}))
TypeError: must be unicode, not str
```

**Comment by tmbo** [comment]
The strings of the python duckling wrapper aren't unicode. so we might need to wrap that when reading the available dimensions from there.

**Comment by oziee** [comment]
i get this error in 0.8.5

**Comment by oziee** [comment]
#365
