### ISSUE TITLE
MITIE is always required

### ISSUE THREAD

**Issue by hobofan** [golastmile/rasa_nlu#7]
I tried to use the spacy backend without installing MITIE & scipy. Installing them resolved the issue.

Error message below:

```
python -m rasa_nlu.train -c config.json
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/rasa_nlu/train.py", line 44, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_nlu/train.py", line 36, in do_train
  File "build/bdist.linux-x86_64/egg/rasa_nlu/train.py", line 23, in create_trainer
  File "build/bdist.linux-x86_64/egg/rasa_nlu/trainers/spacy_sklearn_trainer.py", line 5, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_nlu/classifiers/sklearn_intent_classifier.py", line 2, in <module>
ImportError: No module named mitie
```

**Comment by amn41** [comment]
this was addressed with commit c5a78634291a2797a44152c1e5a959b8b6d49c1a and merged in #16
