### ISSUE TITLE
Error running sklearn backend on windows

### ISSUE THREAD

**Issue by danielcreese** [golastmile/rasa_nlu#72]
I am getting the following error when running:

`python -m rasa_nlu.server -c config.json -e api`

<pre>INFO:root:using spacy + sklearn backend
Traceback (most recent call last):
  File "C:\Users\<USERNAME>\Anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\<USERNAME>\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build\bdist.win-amd64\egg\rasa_nlu\server.py", line 247, in <module>
  File "build\bdist.win-amd64\egg\rasa_nlu\server.py", line 20, in __init__
  File "build\bdist.win-amd64\egg\rasa_nlu\server.py", line 54, in __create_interpreter
  File "build\bdist.win-amd64\egg\rasa_nlu\interpreters\spacy_sklearn_interpreter.py", line 15, in __init__
  File "C:\Users\<USERNAME>\Anaconda2\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "C:\Users\<USERNAME>\Anaconda2\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Users\<USERNAME>\Anaconda2\lib\pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "C:\Users\<USERNAME>\Anaconda2\lib\pickle.py", line 1130, in find_class
    __import__(module)
ImportError: No module named sklearn_intent_classifier</pre>

I have tried switching over to MITIE, but have had no luck getting that to work either.

I am trying to run a model that was exported from api.ai.

Any help solving this issue would be much appreciated.

**Comment by amn41** [comment]
Did you already train a model using the spacy_sklearn backend? e.g. `python -m rasa_nlu.train -c config.json`?

**Comment by pandasasa** [comment]
I also encountered the same problem and have trained model,added model path to the config.json

**Comment by danielcreese** [comment]
Hi,
Thanks for the quick response. Yes, the model appeared to train without any issues.

**Comment by amn41** [comment]
this might be due to a version clash between scikit-learn 0.17 and 0.18. What are you running?

**Comment by ankitbko** [comment]
Facing same issue. Any workaround?

**Comment by ankitbko** [comment]
Fixed it by changing [L59](https://github.com/golastmile/rasa_nlu/blob/master/src/trainers/spacy_sklearn_trainer.py#L59) in `spacy_sklearn_trainer` to open the `classifier_file` as binary.
```python
with open(classifier_file, 'wb') as f:
  cloudpickle.dump(self.intent_classifier, f)
```

**Comment by amn41** [comment]
awesome! thanks for catching that do you want to create a PR?
