### ISSUE TITLE
Visualizer requires mitie but doc doesn't mention

### ISSUE THREAD

**Issue by naoko** [golastmile/rasa_nlu#76]
Hello!
I was going through tutorial and attempt to visualize but got the following error. After installing MITIE, all was happy. Should we note this in the doc or am I overlooking something?

```
$ python -m rasa_nlu.visualize data/demo-rasa.json
192.168.200.1 - - [21/Dec/2016 21:30:12] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.200.1', 56752)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "build/bdist.linux-x86_64/egg/rasa_nlu/visualize.py", line 14, in <lambda>
  File "build/bdist.linux-x86_64/egg/rasa_nlu/visualize.py", line 27, in __init__
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "build/bdist.linux-x86_64/egg/rasa_nlu/visualize.py", line 37, in do_GET
  File "build/bdist.linux-x86_64/egg/rasa_nlu/training_data.py", line 25, in __init__
    from rasa_nlu.tokenizers.mitie_tokenizer import MITIETokenizer
  File "build/bdist.linux-x86_64/egg/rasa_nlu/tokenizers/mitie_tokenizer.py", line 1, in <module>
ImportError: No module named mitie
```

**Comment by thayumaanavan** [comment]
In the visualize file,  doGet method has mitie hardcoded instead of using config.
`training_data = TrainingData(data_file, 'mitie', 'en')`

I guess file should be changed to use config.

**Comment by amn41** [comment]
yes you're totally right! thanks for catching this. Will make a fix soon.

**Comment by amn41** [comment]
Closing this, see #108
