### ISSUE TITLE
ImportError: No module named mitie

### ISSUE THREAD

**Issue by alvin-reyes** [golastmile/rasa_nlu#77]
I keep on getting this error when trying to run the train command.

```
python -m rasa_nlu.train -c config.json
Traceback (most recent call last):
  File "D:\Programs\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Programs\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build\bdist.win32\egg\rasa_nlu\train.py", line 65, in <module>
  File "build\bdist.win32\egg\rasa_nlu\train.py", line 54, in do_train
  File "build\bdist.win32\egg\rasa_nlu\train.py", line 28, in create_trainer
  File "build\bdist.win32\egg\rasa_nlu\trainers\mitie_trainer.py", line 1, in <module>
ImportError: No module named mitie
```

I already have the MITIE-models and config.json setup accordingly

```
{
  "backend": "mitie",
  "path" : "./",
  "mitie_file" : "D:\\Projects\\mities\\english\\total_word_feature_extractor.dat",
  "data" : "./data/demo-restaurants.json"
}
```
Is there something that I might be missing?

**Comment by amn41** [comment]
looks like you still need to install [MITIE](https://github.com/mit-nlp/MITIE), you can do that with

`pip install git+https://github.com/mit-nlp/MITIE.git`
