### ISSUE TITLE
KeyError 'text'

### ISSUE THREAD

**Issue by jordanator** [golastmile/rasa_nlu#91]
I have trained the demo-restaurants.json and booted up a server, but when I query, I get a KeyError Exception

`Exception happened during processing of request from ('127.0.0.1', 43896)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/lalithmohan/.local/lib/python2.7/site-packages/rasa_nlu/server.py", line 75, in <lambda>
    self.server = HTTPServer(('', self.config.port), lambda *args: RasaRequestHandler(self.data_router, *args))
  File "/home/lalithmohan/.local/lib/python2.7/site-packages/rasa_nlu/server.py", line 159, in __init__
    BaseHTTPRequestHandler.__init__(self, *args)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/lalithmohan/.local/lib/python2.7/site-packages/rasa_nlu/server.py", line 201, in do_POST
    self.wfile.write(self.get_response(data_dict))
  File "/home/lalithmohan/.local/lib/python2.7/site-packages/rasa_nlu/server.py", line 175, in get_response
    result = self.data_router.parse(data["text"])
KeyError: 'text'`

I have both the data and mitie_file in the same directory and have installed mitie backend. I also tried sending the key as "text" instead of "q"in the POST, but it gives the wrong intent and entities. I don't know what I'm missing here. Here's my config.json

`{
  "backend": "mitie",
  "path" : "./",
  "mitie_file" : "total_word_feature_extractor.dat",
  "data" : "demo-rasa.json"
}`

**Comment by jordanator** [comment]
After writing `"server_model_dir" : "./model_YYYYMMDD-HHMMSS"` in config.json, it's working
