### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by yogeshhk** [golastmile/rasa_nlu#94]
I am doing restaurants tutorial mentioned at http://rasa-nlu.readthedocs.io/en/latest/tutorial.html#section-tutorial

Doing it spacy_sklearn way

Downloaded spacy and all the models

I had scikit-learn installed, which was 0.18

I had data/demo-rasa.json so mentioned it in the config.json and not demo-restaurants.json

When I fiired following command:
`python -m rasa_nlu.train -c config.json`

I got error: 

> ImportError: cannot import name check_arrays

Thinking that its a scikit version issue (ref: http://stackoverflow.com/questions/29596237/import-check-arrays-from-sklearn) I installed 0.17.1 which gave following error:

> ImportError: No module named model_selection

I am stuck now.. not sure what to do next...any hints?

**Comment by amn41** [comment]
Hi @yogeshhk - we're using scikit-learn 0.18.1 - can you tell me exactly which line throws the importerror?

**Comment by yogeshhk** [comment]
Traceback (most recent call last):
  File "C:\Users\kulkarni\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\kulkarni\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.6.2.3262.win-x86_64\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build\bdist.win-amd64\egg\rasa_nlu\train.py", line 65, in <module>
  File "build\bdist.win-amd64\egg\rasa_nlu\train.py", line 54, in do_train
  File "build\bdist.win-amd64\egg\rasa_nlu\train.py", line 31, in create_trainer

  File "build\bdist.win-amd64\egg\rasa_nlu\trainers\spacy_sklearn_trainer.py", line 8, in <module>
  File "build\bdist.win-amd64\egg\rasa_nlu\classifiers\sklearn_intent_classifier.py", line 1, in <module>
  File "c:\users\kulkarni\appdata\local\enthought\canopy\user\lib\site-packages\sklearn\model_selection\__init__.py", line 1, in <module>
    from ._split import BaseCrossValidator
  File "c:\users\kulkarni\appdata\local\enthought\canopy\user\lib\site-packages\sklearn\model_selection\_split.py", line 36, in <module>
    from ..gaussian_process.kernels import Kernel as GPKernel
  File "c:\users\kulkarni\appdata\local\enthought\canopy\user\lib\site-packages\sklearn\gaussian_process\__init__.py", line 13, in <module>
    from .gpr import GaussianProcessRegressor
  File "c:\users\kulkarni\appdata\local\enthought\canopy\user\lib\site-packages\sklearn\gaussian_process\gpr.py", line 15, in <module>
    from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
  File "c:\users\kulkarni\appdata\local\enthought\canopy\user\lib\site-packages\sklearn\gaussian_process\kernels.py", line 30, in <module>
    from ..metrics.pairwise import pairwise_kernels
  File "c:\users\kulkarni\appdata\local\enthought\canopy\user\lib\site-packages\sklearn\metrics\__init__.py", line 33, in <module>
    from . import cluster
  File "c:\users\kulkarni\appdata\local\enthought\canopy\user\lib\site-packages\sklearn\metrics\cluster\__init__.py", line 23, in <module>
    from .bicluster import consensus_score
  File "c:\users\kulkarni\appdata\local\enthought\canopy\user\lib\site-packages\sklearn\metrics\cluster\bicluster\__init__.py", line 1, in <module>
    from .bicluster_metrics import consensus_score
  File "c:\users\kulkarni\appdata\local\enthought\canopy\user\lib\site-packages\sklearn\metrics\cluster\bicluster\bicluster_metrics.py", line 6, in <module>
    from sklearn.utils.validation import check_arrays
ImportError: cannot import name check_arrays

**Comment by amn41** [comment]
my best guess is there is something up with your installation. I'm not familiar with the canopy distribution, but my advice would be to do a fresh install, with scikit-learn 0.18.1. 
Then open up a python interpreter, and run 
```from sklearn import model_selection```
and see if that throws the same error.

**Comment by yogeshhk** [comment]
Thanks for the suggestion. I removed the Canopy distribution. Installed Minicoda 2 and then compilation seems to be fine. I could train the model and added it to the config.json I ran the server by

`python -m rasa_nlu.server -c config.json`

Then fired the test command from another window:

` curl -XPOST localhost:5000/parse -d '{"q":"I am looking for Chinese food"}' | python -mjson.tool`

It said:

>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    35    0     0  100    35      0    149 --:--:-- --:--:-- --:--:--   149
> No JSON object could be decoded

I tried another test. In browser I pasted:

`http://localhost:5000/parse?q=I am looking for Chinese food`

It gave:

> {"text": "I am looking for Chinese food", "intent": "restaurant_search", "entities": []}

I did not get the correct reply as:
```
{
  "intent" : "restaurant_search",
  "entities" : [
    {
      "start": 8,
      "end": 15,
      "value": "chinese",
      "entity": "cuisine"
    }
  ]
}
```

What could have gone wrong?

My Model training_data.json does have entry like:

```
      {
        "text": "show me chinese restaurants", 
        "intent": "restaurant_search", 
        "entities": [
          {
            "start": 8, 
            "end": 15, 
            "value": "chinese", 
            "entity": "cuisine"
          }
        ]
      }, 
```
I thought it would pick up entities, but did not. Any clues?

**Comment by amn41** [comment]
The example data provided is really just a toy example to show how to use rasa, & doesn't provide enough examples for the spacy NER model to pick up `chinese` as an entity. I'll add a comment about that to the docs :) 

Regarding the issue with your curl POST, my best guess is that the windows version of `cURL` doesn't automatically encode the json data for you. I would suggest doing the request with Postman or a similar API testing tool (or just the python [requests](http://docs.python-requests.org/en/master/) package

**Comment by amn41** [comment]
closing this now. If you are certain the HTTP request is valid & there's an issue on rasa's side, please re-open.
